// <auto-generated />
using System;
using IotMonitor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IotMonitor.Data.Migrations
{
    [DbContext(typeof(IotMonitorDbContext))]
    [Migration("20260603003730_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IotMonitor.Domain.Models.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("DeviceTypeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceTypeCode");

                    b.ToTable("Devices", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("IotMonitor.Domain.Models.DeviceType", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Lifecycle")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Code");

                    b.ToTable("DeviceTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "SENSOR_MODBUS",
                            Lifecycle = 1,
                            Name = "Sensor Modbus",
                            Protocol = "Modbus TCP"
                        },
                        new
                        {
                            Code = "BARRERA_MODBUS",
                            Lifecycle = 2,
                            Name = "Barrera Modbus",
                            Protocol = "Modbus TCP"
                        },
                        new
                        {
                            Code = "SEMAFORO_MODBUS",
                            Lifecycle = 2,
                            Name = "Semaforo Modbus",
                            Protocol = "Modbus TCP"
                        },
                        new
                        {
                            Code = "CAMARA_HTTP",
                            Lifecycle = 2,
                            Name = "Camara HTTP",
                            Protocol = "HTTP"
                        },
                        new
                        {
                            Code = "CARTEL_UDP",
                            Lifecycle = 3,
                            Name = "Cartel UDP",
                            Protocol = "UDP"
                        });
                });

            modelBuilder.Entity("IotMonitor.Domain.Models.HttpConfig", b =>
                {
                    b.HasBaseType("IotMonitor.Domain.Models.Device");

                    b.Property<string>("EndpointPath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.ToTable("HttpConfigs", (string)null);
                });

            modelBuilder.Entity("IotMonitor.Domain.Models.ModbusConfig", b =>
                {
                    b.HasBaseType("IotMonitor.Domain.Models.Device");

                    b.Property<int>("PrimaryCoil")
                        .HasColumnType("int");

                    b.Property<byte>("UnitId")
                        .HasColumnType("tinyint");

                    b.ToTable("ModbusConfigs", (string)null);
                });

            modelBuilder.Entity("IotMonitor.Domain.Models.Device", b =>
                {
                    b.HasOne("IotMonitor.Domain.Models.DeviceType", "DeviceType")
                        .WithMany("Devices")
                        .HasForeignKey("DeviceTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeviceType");
                });

            modelBuilder.Entity("IotMonitor.Domain.Models.HttpConfig", b =>
                {
                    b.HasOne("IotMonitor.Domain.Models.Device", null)
                        .WithOne()
                        .HasForeignKey("IotMonitor.Domain.Models.HttpConfig", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IotMonitor.Domain.Models.ModbusConfig", b =>
                {
                    b.HasOne("IotMonitor.Domain.Models.Device", null)
                        .WithOne()
                        .HasForeignKey("IotMonitor.Domain.Models.ModbusConfig", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IotMonitor.Domain.Models.DeviceType", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
