// <auto-generated />
using System;
using IotMonitor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IotMonitor.Data.Migrations
{
    [DbContext(typeof(IotMonitorDbContext))]
    [Migration("20260613043400_AddUdpDeviceEntity")]
    partial class AddUdpDeviceEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IotMonitor.Data.Entities.DeviceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("DeviceTypeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceTypeCode");

                    b.ToTable("Devices", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("IotMonitor.Data.Entities.DeviceTypeEntity", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Lifecycle")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Code");

                    b.ToTable("DeviceTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "SENSOR_MODBUS",
                            Lifecycle = 1,
                            Name = "Sensor Modbus TCP"
                        },
                        new
                        {
                            Code = "CAMARA_HTTP",
                            Lifecycle = 2,
                            Name = "Cámara HTTP"
                        },
                        new
                        {
                            Code = "BARRERA_MODBUS",
                            Lifecycle = 2,
                            Name = "Barrera Modbus TCP"
                        },
                        new
                        {
                            Code = "SEMAFORO_MODBUS",
                            Lifecycle = 2,
                            Name = "Semáforo Modbus TCP"
                        },
                        new
                        {
                            Code = "CARTEL_UDP",
                            Lifecycle = 3,
                            Name = "Cartel LED UDP"
                        });
                });

            modelBuilder.Entity("IotMonitor.Data.Entities.HttpDeviceEntity", b =>
                {
                    b.HasBaseType("IotMonitor.Data.Entities.DeviceEntity");

                    b.Property<string>("EndpointPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("HttpConfigs", (string)null);
                });

            modelBuilder.Entity("IotMonitor.Data.Entities.ModbusDeviceEntity", b =>
                {
                    b.HasBaseType("IotMonitor.Data.Entities.DeviceEntity");

                    b.Property<int>("PrimaryCoil")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.ToTable("ModbusConfigs", (string)null);
                });

            modelBuilder.Entity("IotMonitor.Data.Entities.UdpDeviceEntity", b =>
                {
                    b.HasBaseType("IotMonitor.Data.Entities.DeviceEntity");

                    b.ToTable("UdpDevices");
                });

            modelBuilder.Entity("IotMonitor.Data.Entities.DeviceEntity", b =>
                {
                    b.HasOne("IotMonitor.Data.Entities.DeviceTypeEntity", "DeviceType")
                        .WithMany("Devices")
                        .HasForeignKey("DeviceTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeviceType");
                });

            modelBuilder.Entity("IotMonitor.Data.Entities.HttpDeviceEntity", b =>
                {
                    b.HasOne("IotMonitor.Data.Entities.DeviceEntity", null)
                        .WithOne()
                        .HasForeignKey("IotMonitor.Data.Entities.HttpDeviceEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IotMonitor.Data.Entities.ModbusDeviceEntity", b =>
                {
                    b.HasOne("IotMonitor.Data.Entities.DeviceEntity", null)
                        .WithOne()
                        .HasForeignKey("IotMonitor.Data.Entities.ModbusDeviceEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IotMonitor.Data.Entities.UdpDeviceEntity", b =>
                {
                    b.HasOne("IotMonitor.Data.Entities.DeviceEntity", null)
                        .WithOne()
                        .HasForeignKey("IotMonitor.Data.Entities.UdpDeviceEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IotMonitor.Data.Entities.DeviceTypeEntity", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
