<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.7" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\IotMonitor.Domain\IotMonitor.Domain.csproj" />
    <ProjectReference Include="..\..\src\IotMonitor.Application\IotMonitor.Application.csproj" />
    <ProjectReference Include="..\..\src\IotMonitor.Data\IotMonitor.Data.csproj" />
  </ItemGroup>

</Project>
